# Generated by Django 2.2.4 on 2021-08-08 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USWDML',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.FloatField()),
                ('t_state', models.CharField(max_length=255)),
                ('p_name', models.TextField()),
                ('p_year', models.FloatField()),
                ('p_tnum', models.FloatField()),
                ('p_cap', models.FloatField()),
                ('t_manu', models.TextField()),
                ('t_model', models.TextField()),
                ('t_cap', models.FloatField()),
                ('t_hh', models.CharField(max_length=255)),
                ('x_long', models.FloatField()),
                ('y_lat', models.FloatField()),
            ],
        ),
    ]
