# Generated by Django 2.2.4 on 2021-08-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USWTDB', '0003_auto_20210809_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uswdml',
            name='case_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='uswdml',
            name='p_cap',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uswdml',
            name='p_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='uswdml',
            name='p_tnum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='uswdml',
            name='p_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='uswdml',
            name='t_cap',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uswdml',
            name='t_manu',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='uswdml',
            name='t_state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uswdml',
            name='x_long',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uswdml',
            name='y_lat',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
