# Generated by Django 2.2.4 on 2021-08-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USWTDB', '0004_auto_20210809_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uswdml',
            name='p_year',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
